### ISSUE TITLE
Error in view objective menu

### ISSUE THREAD

**Issue by juliusoka** [cmss13-devs/cmss13#1101]
Soo when i try to complete my objective as IO to upload some data (we got around 25 Data)... this happen
A fatal exception has occurred at 002B:C562F1B7 in TGUI.

TypeError: Unable to get property 'color' of undefined or null reference
   at Anonymous function (http://127.0.0.1:50231/tmp5736/tgui.bundle.js:1:526853)
   at Anonymous function (http://127.0.0.1:50231/tmp5736/tgui.bundle.js:1:42757)
   at map (http://127.0.0.1:50231/tmp5736/tgui.bundle.js:1:97921)
   at c (http://127.0.0.1:50231/tmp5736/tgui.bundle.js:1:526714)
   at Ie (http://127.0.0.1:50231/tmp5736/tgui.bundle.js:1:168963)
   at Anonymous function (http://127.0.0.1:50231/tmp5736/tgui.bundle.js:1:172077)
   at Fe (http://127.0.0.1:50231/tmp5736/tgui.bundle.js:1:171853)
   at Anonymous function (http://127.0.0.1:50231/tmp5736/tgui.bundle.js:1:173611)
   at Pe (http://127.0.0.1:50231/tmp5736/tgui.bundle.js:1:173519)
   at Anonymous function (http://127.0.0.1:50231/tmp5736/tgui.bundle.js:1:171353)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0E; .NET4.0C; .NET CLR 3.5.30729; .NET CLR 2.0.50727; .NET CLR 3.0.30729; InfoPath.3; Zoom 3.6.0)
State: {"ckey":"frzlunar","interface":"TechMemories","window":{"key":"[0x21010588]-main","size":null,"fancy":1,"locked":0}}

**Comment by mullenpaul** [comment]
I've seen this before. I seemed to have an issue but a friend of mine did not, for the same set of objectives.

**Comment by Segrain** [comment]
Duplicate indeed. Still need to get to fixing it, though.
