### ISSUE TITLE
'access level' undefined error in ARES console TGUI when requesting access 

### ISSUE THREAD

**Issue by stagda** [cmss13-devs/cmss13#4289]
### Testmerges

 BYOND Version: 515.1610 Server revision compiled on: 2023-08-30T12:16:46+00:00 Master commit: 4ad2587f9a8910c34e476d26305acbc829a4fd20 The following pull requests are currently test merged: #4246: 'Move xeno grab cooldown change to just ctrl+click logic' by Drulikar at commit d4a4aebeea #4224: 'ARES Change Holder' by realforest2001 at commit eeb44ebd6a #4063: 'Yautja Change Holder' by realforest2001 at commit 377eeb300e #4274: 'Add flanking possiblities to the lifeboat by adding two clamp with doors on each exterior side.' by Huffie56 at commit 3694dbfcc4 #4241: 'notify ghosts' by harryob at commit 10d2fa7883 #4280: 'Lesser drone changes' by morrowwolf at commit 324a59f75c  Local commit: 6c87dfdd4dc889d557619f1cb2c10a5723a1f3f6 TGS version: 5.15.1 DMAPI version: 5.6.1

### Description of the bug

When trying to request an ARES access ticket as a level 2 reporter when playing as ASO I get the below error in the UI. This error continues to appear for me on any console I tried to request an access ticket on even if I close and re-open it. 

ReferenceError: 'access_level' is undefined
   at f (http://cdn.cm-ss13.com/live/0b/asset.0b476970e27224211e02eedae4f9c6cc.js:1:831290)
   at Ie (http://cdn.cm-ss13.com/live/0b/asset.0b476970e27224211e02eedae4f9c6cc.js:1:161096)
   at Anonymous function (http://cdn.cm-ss13.com/live/0b/asset.0b476970e27224211e02eedae4f9c6cc.js:1:161364)
   at Te (http://cdn.cm-ss13.com/live/0b/asset.0b476970e27224211e02eedae4f9c6cc.js:1:161342)
   at Anonymous function (http://cdn.cm-ss13.com/live/0b/asset.0b476970e27224211e02eedae4f9c6cc.js:1:162959)
   at Me (http://cdn.cm-ss13.com/live/0b/asset.0b476970e27224211e02eedae4f9c6cc.js:1:162828)
   at Pe (http://cdn.cm-ss13.com/live/0b/asset.0b476970e27224211e02eedae4f9c6cc.js:1:164988)
   at Anonymous function (http://cdn.cm-ss13.com/live/0b/asset.0b476970e27224211e02eedae4f9c6cc.js:1:163486)
   at Me (http://cdn.cm-ss13.com/live/0b/asset.0b476970e27224211e02eedae4f9c6cc.js:1:163025)
   at Pe (http://cdn.cm-ss13.com/live/0b/asset.0b476970e27224211e02eedae4f9c6cc.js:1:164988)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0; Zoom 3.6.0)
State: {"ckey":"stagda","interface":"WorkingJoe","window":{"key":"[0x20051ee]-main","size":null,"fancy":1,"locked":0}}

### What's the difference with what should have happened?

Should be able to request an access ticket and have the UI appear as normal.

### How do we reproduce this bug?

1. Be ASO
2. Click request access ticket on an ARES console
3.
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by realforest2001** [comment]
Fixed!
