### ISSUE TITLE
"Data" Tab of Intel Objectives is Broken

### ISSUE THREAD

**Issue by Loonite** [cmss13-devs/cmss13#5509]
### Testmerges

#5086: 'Adds the XM51 Breaching Scattergun' by VileBeggar at commit 1a300eff40 #5337: 'Fixes playing cards' by fira at commit 3b08cf34e4 #5228: 'Reduces the burst multiplier on the M39' by VileBeggar at commit 74a1f99dc9 #5397: 'A slurry of Bigred changes' by spartanbobby at commit 57f6fc3951 #5402: 'Databasing whitelists' by realforest2001 at commit cd12902fef #5007: 'Project ARES TM Holder (v4)' by realforest2001 at commit 2b8b3d283f #5165: 'Ports Mapping Backend updates' by fira at commit 1fb4bea8ca #5493: 'React Migration - part 2' by mullenpaul at commit 0016ed513e

### Description of the bug

Any attempt to access the Data tab of the Intelligence Objectives menu is met with:

Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
   at Ts (http://cdn.cm-ss13.com/live/5c/asset.5cad5b2ee4c88b9bd9593dc16f74f0dc.js:1:116883)
   at f (http://cdn.cm-ss13.com/live/5c/asset.5cad5b2ee4c88b9bd9593dc16f74f0dc.js:1:57957)
   at p (http://cdn.cm-ss13.com/live/5c/asset.5cad5b2ee4c88b9bd9593dc16f74f0dc.js:1:59320)
   at g (http://cdn.cm-ss13.com/live/5c/asset.5cad5b2ee4c88b9bd9593dc16f74f0dc.js:1:61404)
   at jl (http://cdn.cm-ss13.com/live/5c/asset.5cad5b2ee4c88b9bd9593dc16f74f0dc.js:1:72975)
   at kc (http://cdn.cm-ss13.com/live/5c/asset.5cad5b2ee4c88b9bd9593dc16f74f0dc.js:1:121892)
   at vs (http://cdn.cm-ss13.com/live/5c/asset.5cad5b2ee4c88b9bd9593dc16f74f0dc.js:1:109311)
   at xs (http://cdn.cm-ss13.com/live/5c/asset.5cad5b2ee4c88b9bd9593dc16f74f0dc.js:1:109245)
   at ps (http://cdn.cm-ss13.com/live/5c/asset.5cad5b2ee4c88b9bd9593dc16f74f0dc.js:1:109108)
   at ls (http://cdn.cm-ss13.com/live/5c/asset.5cad5b2ee4c88b9bd9593dc16f74f0dc.js:1:106225)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729)
State: {"ckey":"loonite","interface":"TechMemories","window":{"key":"[0x210312a2]-main","size":null,"fancy":1,"locked":0}}

### What's the difference with what should have happened?

The expected behavior is for the Data tab to function as normal, showing collected passcodes to discs.

### How do we reproduce this bug?

1. Attempt to access the Data tab of the Intelligence Objectives page, either from the user interface or from an actual terminal in-game.
...

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [ ] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by ItsVyzo** [comment]
Potentially related to #5493

**Comment by realforest2001** [comment]
Same applies to Other tab.

**Comment by mullenpaul** [comment]
I have just pushed a fix, this should resolve it

**Comment by ItsVyzo** [comment]
Tested - Fixed
