### ISSUE TITLE
TGUI issue when opening Biomass Analyzer UI.

### ISSUE THREAD

**Issue by dadlips** [cmss13-devs/cmss13#6313]
### Testmerges

N/A

### Round ID

22272

### Description of the bug

A fatal exception has occurred at 002B:C562F1B7 in TGUI.The current application will be terminated.Send the copy of the following stack trace to an authorizedWeyland-Yutani incident handler at https://github.com/cmss13-devs/cmss13/issues.Thank you for your cooperation. 
 ReferenceError: 'useState' is undefined
   at a (http://cdn.cm-ss13.com/live/b6/asset.b68ebac60e5e4aaaf36c855567b302fd.js:292:168015)
   at Wl (http://cdn.cm-ss13.com/live/b6/asset.b68ebac60e5e4aaaf36c855567b302fd.js:9:65530)
   at _u (http://cdn.cm-ss13.com/live/b6/asset.b68ebac60e5e4aaaf36c855567b302fd.js:9:119113)
   at Pu (http://cdn.cm-ss13.com/live/b6/asset.b68ebac60e5e4aaaf36c855567b302fd.js:9:114751)
   at nd (http://cdn.cm-ss13.com/live/b6/asset.b68ebac60e5e4aaaf36c855567b302fd.js:9:114685)
   at Pl (http://cdn.cm-ss13.com/live/b6/asset.b68ebac60e5e4aaaf36c855567b302fd.js:9:114538)
   at dc (http://cdn.cm-ss13.com/live/b6/asset.b68ebac60e5e4aaaf36c855567b302fd.js:9:110751)
   at Cu (http://cdn.cm-ss13.com/live/b6/asset.b68ebac60e5e4aaaf36c855567b302fd.js:9:109731)
   at S (http://cdn.cm-ss13.com/live/b6/asset.b68ebac60e5e4aaaf36c855567b302fd.js:33:1556)
   at L (http://cdn.cm-ss13.com/live/b6/asset.b68ebac60e5e4aaaf36c855567b302fd.js:33:1922)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729)
State: {"ckey":"smellyhippie","interface":"XenomorphExtractor","window":{"key":"[0x2025d9d]-main","size":null,"fancy":1,"locked":0}}

#6188 Opening the biomass analyzer's UI, you're welcomed with this. There didn't seem to be any runtimes in the server logs.

### What's the difference with what should have happened?

UI shouldn't crash when opening the analyzer. Respawning the analyzer did not help.

### How do we reproduce this bug?

1. Open the anayzer's UI
2. It crashes with the above error.

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by kiVts** [comment]
fixed in the next round

**Comment by kiVts** [comment]
okay _maybe_ not in the next round but whenever I get someone to update the tm, which should be soon
