### ISSUE TITLE
Overwatch TGUI Crash When Saving Coords Name/Comment

### ISSUE THREAD

**Issue by dadlips** [cmss13-devs/cmss13#6366]
### Testmerges

N/A

### Round ID

22478

### Description of the bug

       



Overwatch Console

×

Main Dashboard

Squad Roles



Squad Monitor



Orbital Bombardment



Tactical Map

Orbital Bombardment

186

LONGITUDE

-290

LATITUDE

Ready

STATUS

Fire

Save

Max 3 stored coordinates. Will overwrite oldest first.

LONG. LAT. COMMENT  
186 -290 

.
 

 

 

  \+++++\@@@@@@@@@@/++++\@@@@@@@@@@/+++++/
  \+++++\@``````@/++*+*+\@``````@/+++++/
   \+++++\@````@/++++++++\@````@/+++++/
    \+++++\@``@/++++++++++\@``@/+++++/
     \+++++\@@/+++++/\+++++\@@/+++++/
      \+++*+\/+*+++/@@\+++++\/+++++/
       \++++++++++/@``@\++++++++++/
        \++++++*+/@````@\++++++++/
         \++++++/@@@@@@@@\++++++/
 
 
A fatal exception has occurred at 002B:C562F1B7 in TGUI.The current application will be terminated.Send the copy of the following stack trace to an authorizedWeyland-Yutani incident handler at https://github.com/cmss13-devs/cmss13/issues.Thank you for your cooperation. 
 TypeError: Circular reference in value argument not supported
   at D (http://cdn.cm-ss13.com/live/2c/asset.2cad297a31880c74247b4d3b54bce4b5.js:384:101878)
   at stringify (http://cdn.cm-ss13.com/live/2c/asset.2cad297a31880c74247b4d3b54bce4b5.js:384:102164)
   at Byond.sendMessage (http://127.0.0.1:50103/tgui-window-1.html:205:7)
   at O (http://cdn.cm-ss13.com/live/2c/asset.2cad297a31880c74247b4d3b54bce4b5.js:100:3433)
   at onChange (http://cdn.cm-ss13.com/live/2c/asset.2cad297a31880c74247b4d3b54bce4b5.js:283:357635)
   at onBlur (http://cdn.cm-ss13.com/live/2c/asset.2cad297a31880c74247b4d3b54bce4b5.js:178:1729)
   at Fn (http://cdn.cm-ss13.com/live/2c/asset.2cad297a31880c74247b4d3b54bce4b5.js:9:17192)
   at os (http://cdn.cm-ss13.com/live/2c/asset.2cad297a31880c74247b4d3b54bce4b5.js:9:17351)
   at ss (http://cdn.cm-ss13.com/live/2c/asset.2cad297a31880c74247b4d3b54bce4b5.js:9:17408)
   at tl (http://cdn.cm-ss13.com/live/2c/asset.2cad297a31880c74247b4d3b54bce4b5.js:9:38797)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729)
State: {"ckey":"smellyhippie","interface":"OverwatchConsole","window":{"key":"[0x2007777]-main","size":null,"fancy":1,"locked":0}}

TypeError: Circular reference in value argument not supported
   at D (http://cdn.cm-ss13.com/live/2c/asset.2cad297a31880c74247b4d3b54bce4b5.js:384:101878)
   at stringify (http://cdn.cm-ss13.com/live/2c/asset.2cad297a31880c74247b4d3b54bce4b5.js:384:102164)
   at Byond.sendMessage (http://127.0.0.1:50103/tgui-window-1.html:205:7)
   at O (http://cdn.cm-ss13.com/live/2c/asset.2cad297a31880c74247b4d3b54bce4b5.js:100:3433)
   at onChange (http://cdn.cm-ss13.com/live/2c/asset.2cad297a31880c74247b4d3b54bce4b5.js:283:357635)
   at onBlur (http://cdn.cm-ss13.com/live/2c/asset.2cad297a31880c74247b4d3b54bce4b5.js:178:1729)
   at Fn (http://cdn.cm-ss13.com/live/2c/asset.2cad297a31880c74247b4d3b54bce4b5.js:9:17192)
   at os (http://cdn.cm-ss13.com/live/2c/asset.2cad297a31880c74247b4d3b54bce4b5.js:9:17351)
   at ss (http://cdn.cm-ss13.com/live/2c/asset.2cad297a31880c74247b4d3b54bce4b5.js:9:17408)
   at tl (http://cdn.cm-ss13.com/live/2c/asset.2cad297a31880c74247b4d3b54bce4b5.js:9:38797)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729)
State: {"ckey":"smellyhippie","interface":"OverwatchConsole","window":{"key":"[0x2007777]-main","size":null,"fancy":1,"locked":0}}

TypeError: Circular reference in value argument not supported
   at D (http://cdn.cm-ss13.com/live/2c/asset.2cad297a31880c74247b4d3b54bce4b5.js:384:101878)
   at stringify (http://cdn.cm-ss13.com/live/2c/asset.2cad297a31880c74247b4d3b54bce4b5.js:384:102164)
   at Byond.sendMessage (http://127.0.0.1:50103/tgui-window-1.html:205:7)
   at O (http://cdn.cm-ss13.com/live/2c/asset.2cad297a31880c74247b4d3b54bce4b5.js:100:3433)
   at onChange (http://cdn.cm-ss13.com/live/2c/asset.2cad297a31880c74247b4d3b54bce4b5.js:283:357635)
   at onBlur (http://cdn.cm-ss13.com/live/2c/asset.2cad297a31880c74247b4d3b54bce4b5.js:178:1729)
   at Fn (http://cdn.cm-ss13.com/live/2c/asset.2cad297a31880c74247b4d3b54bce4b5.js:9:17192)
   at os (http://cdn.cm-ss13.com/live/2c/asset.2cad297a31880c74247b4d3b54bce4b5.js:9:17351)
   at ss (http://cdn.cm-ss13.com/live/2c/asset.2cad297a31880c74247b4d3b54bce4b5.js:9:17408)
   at tl (http://cdn.cm-ss13.com/live/2c/asset.2cad297a31880c74247b4d3b54bce4b5.js:9:38797)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729)
State: {"ckey":"smellyhippie","interface":"OverwatchConsole","window":{"key":"[0x2007777]-main","size":null,"fancy":1,"locked":0}}

TypeError: Circular reference in value argument not supported
   at D (http://cdn.cm-ss13.com/live/2c/asset.2cad297a31880c74247b4d3b54bce4b5.js:384:101878)
   at stringify (http://cdn.cm-ss13.com/live/2c/asset.2cad297a31880c74247b4d3b54bce4b5.js:384:102164)
   at Byond.sendMessage (http://127.0.0.1:50103/tgui-window-1.html:205:7)
   at O (http://cdn.cm-ss13.com/live/2c/asset.2cad297a31880c74247b4d3b54bce4b5.js:100:3433)
   at onChange (http://cdn.cm-ss13.com/live/2c/asset.2cad297a31880c74247b4d3b54bce4b5.js:283:357635)
   at onBlur (http://cdn.cm-ss13.com/live/2c/asset.2cad297a31880c74247b4d3b54bce4b5.js:178:1729)
   at Fn (http://cdn.cm-ss13.com/live/2c/asset.2cad297a31880c74247b4d3b54bce4b5.js:9:17192)
   at os (http://cdn.cm-ss13.com/live/2c/asset.2cad297a31880c74247b4d3b54bce4b5.js:9:17351)
   at ss (http://cdn.cm-ss13.com/live/2c/asset.2cad297a31880c74247b4d3b54bce4b5.js:9:17408)
   at tl (http://cdn.cm-ss13.com/live/2c/asset.2cad297a31880c74247b4d3b54bce4b5.js:9:38797)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729)
State: {"ckey":"smellyhippie","interface":"OverwatchConsole","window":{"key":"[0x2007777]-main","size":null,"fancy":1,"locked":0}}

Weyland-Yutani (c) 2100-2182 Building better user interfaces. 
  
marine bravo radio headset

![x1HOwofZj6](https://github.com/cmss13-devs/cmss13/assets/139605145/35496e40-7066-4135-bb16-2c0134337890)

### What's the difference with what should have happened?

When adding a 'comment' to your coords as pictured above, TGUI crashes.

### How do we reproduce this bug?

1. Get some coords, and save them.
2. Try to change the name/comment of the coords.
3. Overwatch TGUI crash
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by vero5123** [comment]
```
                onChange={(e, value) =>
                  act('change_coordinate_comment', {
                    comment: value,
                    index: coords.index,
                  })
                }
```
seems to fix it

**Comment by vero5123** [comment]
maints said issues like theis should be resolved once everything gets migrated to tsx.
