### ISSUE TITLE
Overwatch console has a fatal error when a backslash is typed into the search bar

### ISSUE THREAD

**Issue by GoodWheatley** [cmss13-devs/cmss13#6949]
### Testmerges

#6334: 'Xenomorph Endgame' by Git-Nivrak at commit 8d2cc8fb83 #6071: '[V] Sorokyne Strata: Expanded Small corridors, removed 3000 unused tiles, Xenos can now weed everything except LZ's and surrounding of LZ's, allow LAZ for CAS inside structures with light blue Areas on Tacmap (glass ceiling hallways)' by Venuska1117 at commit 817ed55a47 #6248: 'New Map: LV-759 Hybrisa Prospera' by Zenith00000 at commit 993839df4b #6682: 'Hugged changes' by zzzmike at commit 901f664a71 #6860: 'Mentor New Player Markers' by realforest2001 at commit e8eef22705 #6855: 'Non folding plasteel barricade' by Blundir at commit d277c0e46f #6824: 'Human bursting sounds + sprite, new hugging sounds' by Blundir at commit e5f8b1ceae #4818: 'Synthetic Wrist Computer' by realforest2001 at commit 39af8a5094 #6820: 'Updates close backpack icon' by Blundir at commit e6e1e493fa #6808: 'Attachments resprite' by Blundir at commit 4fbc87b064

### Round ID

23512

### Description of the bug

I was trying to search up a marine to transfer to alpha squad when i accidentally set them to aSL. trying to delete the name in the search bar so I could set the SL back to SL, I hit a few extra keys (maybe the backslash?) and the computer had a fatal error.
UPDATE: The console consistently crashes when you type a backslash into the search bar

### What's the difference with what should have happened?

The overwatch computer not having a fatal error

### How do we reproduce this bug?

1) type a backslash into the search bar of an overwatch console
2) computer dies

SyntaxError: Syntax error in regular expression
   at se (http://cdn.cm-ss13.com/live/b9/asset.b98344bd9ec3c5570a49da4034c41402.js:384:129205)
   at Anonymous function (http://cdn.cm-ss13.com/live/b9/asset.b98344bd9ec3c5570a49da4034c41402.js:283:363511)
   at Anonymous function (http://cdn.cm-ss13.com/live/b9/asset.b98344bd9ec3c5570a49da4034c41402.js:384:23202)
   at filter (http://cdn.cm-ss13.com/live/b9/asset.b98344bd9ec3c5570a49da4034c41402.js:384:87346)
   at p (http://cdn.cm-ss13.com/live/b9/asset.b98344bd9ec3c5570a49da4034c41402.js:283:361384)
   at nl (http://cdn.cm-ss13.com/live/b9/asset.b98344bd9ec3c5570a49da4034c41402.js:9:65539)
   at gu (http://cdn.cm-ss13.com/live/b9/asset.b98344bd9ec3c5570a49da4034c41402.js:9:119140)
   at mu (http://cdn.cm-ss13.com/live/b9/asset.b98344bd9ec3c5570a49da4034c41402.js:9:114777)
   at nd (http://cdn.cm-ss13.com/live/b9/asset.b98344bd9ec3c5570a49da4034c41402.js:9:114711)
   at gs (http://cdn.cm-ss13.com/live/b9/asset.b98344bd9ec3c5570a49da4034c41402.js:9:114564)

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by GoodWheatley** [comment]
Issue updated to include that the console consistently crashes when you type a backslash into the search bar.

**Comment by ItsVyzo** [comment]
unable to reproduce on live

**Comment by MistChristmas** [comment]
Fixed of #8544
